
services:
  postgres:
    image: postgres:15-alpine
    container_name: challenge_postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER:-hassan}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-ecommercedb}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: challenge_redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: challenge_backend
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER:-hassan}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_NAME=${DATABASE_NAME:-ecommercedb}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  frontend:
    image: node:22-alpine
    container_name: challenge_frontend
    working_dir: /app
    volumes:
      - ./front:/app
    command: sh -c "corepack enable pnpm && CI=true pnpm install && pnpm dev"
    ports:
      - "3001:3000"

volumes:
  pgdata:
  redisdata:
