server {
    listen 80;
    server_name localhost;

    # Gzip Compression Config
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esto es clave para las Single Page Applications (React Router)
        # Si la ruta no existe fisicamente como archivo ($uri) ni como directorio ($uri/), manda al index.html
        try_files $uri $uri/ /index.html;
    }

    # Configuraciones extra para que no guarde cache de archivos html (para que always cargue la ultima version del index)
    location ~* \.html$ {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
